### PR TITLE
Fixed the example for cd

### PR DESCRIPTION
**Pull request by Taz03**
used proper windows file system path in the example

### CODE REVIEW

**Comment by Taz03** [comment]
@thomas-xin hi, weird request but can u add the `hactoberfest-accepted` to this pr?

**Comment by thomas-xin** [comment]
@Taz03 what does that mean?

**Comment by Taz03** [comment]
@thomas-xin the hacktoberfest-accepted tag 
image

**Comment by thomas-xin** [comment]
Like that?

**Comment by Taz03** [comment]
wrong spelling, there was a typo on my first message

**Comment by Taz03** [comment]
also i'll need to wait around an hour to see if that counts, thanks anyways

**Comment by Taz03** [comment]
adding the hacktoberfest label to the pr will be best option ppl participating in the event will contribute to ur project, it'll also provide some reach. check out the event

**Comment by Taz03** [comment]
> adding the hacktoberfest label to the pr will be best option ppl participating in the event will contribute to ur project, it'll also provide some reach. check out the event

hacktoberfest lable to the repo*, typo again :cry:

**Comment by Taz03** [comment]
ok the site updated this won't work, thanks for helping tho

u'll need to add the `hacktoberfest` topic to the repo
image
here

**Comment by Taz03** [comment]
image
wait nvm it worked

love u :heart:

**Comment by Taz03** [comment]
ohh maybe coz u added the topic

**Pull request merged**
