### PR TITLE
More README.md Adjusments 

### PR DESCRIPTION
**Pull request by LedaThemis**
* Corrected some minor inconsistencies.
* Added more steps in the Installing Miza section.
* Added Badges
* Minimized HTML usage for easier editing/contributing.
* Fixed some issues with spacing.
* "The Typical Typo Correction"
* Changed Section IDs to easier names for better reference and look in address bar. 
` Example: "hosting-miza-section" -> "Hosting-Miza")`

Would love to hear your thoughts about the badges!
There were many options that I will list below(that you might want to implement them later):

Discord GitHub repo size GitHub watchers

and there is also different styles:

Plastic:

GitHub repo size
Flat:

GitHub repo size
Flat-Square:

GitHub repo size
For-the-Badge:

GitHub repo size
Social:

GitHub repo size

> *All Badges are fetched from [Shields IO](https://shields.io/)'s API*

### CODE REVIEW

**Comment by thomas-xin** [comment]
Badges look great! Plastic style looks the best out of those in my opinion

**Comment by ghost** [comment]
I like the badges! Although I preferred when the text under the first "Miza" header was centralized C:

**Comment by ghost** [comment]
Actually, would it be possible to centralize the buttons and text under them as well? The rest works just fine I think

**Comment by LedaThemis** [comment]
that's weird, it's supposed to be centralized. I will check it out

**Pull request merged**
